### ISSUE TITLE
intel ssdpeknw512g8h not detected

### ISSUE THREAD

**Issue by carloscompleto** [ashaduri/gsmartcontrol#63] opened 2024-08-11 00:10 UTC
**Version and Environment**
 - GSmartControl version: 1.1.4
 - OS: hiren's boot cd

**Describe the Bug**
intel ssdpeknw512g8h not detected

**Comment by ashaduri** [comment] 2024-08-11 06:39
Duplicate of #4

**Closed as completed by ashaduri** 2024-08-11 06:39 UTC
Labels: bug, duplicate, enhancement
