### ISSUE TITLE
On Windows 8.1 NVME disk connected to the onboard M2 connector showed "UNKNOWN"

### ISSUE THREAD

**Issue by vasile2024** [ashaduri/gsmartcontrol#64] opened 2024-10-03 14:29 UTC
on 2 motherboard i have,, ( Gigabyte GA-Z170X and MSI Z170A )
GSmartcontrol (on Windows 8.1) are showing "UNKNOWN" state of he drive, no name, no s.m.a.r.t
other older (2021)  softwares (nirsoft... diskgenius...victoria) are showing correct datas of NVME

on the MSI Z170A that have 2 different M2 slots on both of them the disks are identified as "UNKNOWN"
tried with various brands ( Patriot, crucial, intel,)

![unknown](https://github.com/user-attachments/assets/e8100388-4639-4d67-bb37-a0a547123be4)

**Comment by ashaduri** [comment] 2024-10-04 08:18
Duplicate of #4

**Closed as completed by ashaduri** 2024-10-04 08:18 UTC
Labels: bug, duplicate, enhancement
