### ISSUE TITLE
errors at startup & failure to recognize Samsung EVO 960

### ISSUE THREAD

**Issue by ghost** [ashaduri/gsmartcontrol#3] opened 2021-04-23 09:29 UTC
The issue is that the gsmartcontrol (istalled with apt-get on Ubuntu 20.04, version: 1.1.3) produces lots of errors at runtime, which are outputted to the console. It also fails to parse the "Samsung EVO 960" smart status (which I believe is a quite popular budget SSD).

```
<error> [gtk] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Model Number"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "PCI Vendor/Subsystem ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "IEEE OUI Identifier"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Total NVM Capacity"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Unallocated NVM Capacity"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Controller ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Number of Namespaces"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Namespace 1 Size/Capacity"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Namespace 1 Utilization"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Namespace 1 Formatted LBA Size"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Namespace 1 IEEE EUI-64"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Firmware Updates (0x16)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional Admin Commands (0x0007)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional NVM Commands (0x001f)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Maximum Data Transfer Size"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Warning  Comp. Temp. Threshold"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Critical Comp. Temp. Threshold"
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section(): Unknown section encountered.
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
```

Best,
Mateusz

**Comment by ashaduri** [comment] 2021-04-23 10:44
Duplicate of #4 .

The error messages are harmless and have been mostly fixed in git main.

**Closed as completed by ashaduri** 2021-04-23 10:44 UTC
Labels: duplicate
