### ISSUE TITLE
ADATA SWORDFISH SATA M.2 support

### ISSUE THREAD

**Issue by Yousha** [ashaduri/gsmartcontrol#66] opened 2024-10-20 13:00 UTC
**Version and Environment**
 - GSmartControl version: 1.1.4 64bit
 - Platform: Windows 10 64bit build 19045.5011
 - Infrastucture: ASUS FX505DT with AMD Ryzen 7 3750H CPU

**Describe the Bug**
The application does NOT detect ADATA SWORDFISH SSD M.2
It is unknown

**To Reproduce**
1. Install an ADATA SWORDFISH M.2 SSD
2. Now run the application and see the result.

**Screenshots**
![Screenshot 2024-10-20 162642](https://github.com/user-attachments/assets/4c32bcce-3246-4474-930b-f84c8bef7f41)

**Additional Context**
Drive database is already updated.
Preferences are default.
Target SSD firmware is up to date.
ALL MsVisual C++ redistributable runtimes are installed and up to date.
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

SmartCtl output:
```
smartctl 7.2 2020-12-30 r5155 [x86_64-w64-mingw32-w10-b19045] (sf-7.2-1)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       ADATA SWORDFISH
Serial Number:                      ...
Firmware Version:                   V9002s94
PCI Vendor/Subsystem ID:            0x10ec
IEEE OUI Identifier:                0x00e04c
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          1,000,204,886,016 [1.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            4ce000 0001570000
Local Time is:                      Sun Oct 20 16:30:49 2024 IST
Firmware Updates (0x02):            1 Slot
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x0014):     DS_Mngmt Sav/Sel_Feat
Log Page Attributes (0x02):         Cmd_Eff_Lg
Maximum Data Transfer Size:         32 Pages
Warning  Comp. Temp. Threshold:     100 Celsius
Critical Comp. Temp. Threshold:     110 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     8.00W       -        -    0  0  0  0        0   50000
 1 +     4.00W       -        -    1  1  1  1        0   50000
 2 +     3.00W       -        -    2  2  2  2        0   50000
 3 -   0.0500W       -        -    3  3  3  3     4000   50000
 4 -   0.0080W       -        -    4  4  4  4     8000  100000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
```

**Comment by ashaduri** [comment] 2024-10-23 09:23
Duplicate of #4

**Closed as completed by ashaduri** 2024-10-23 09:23 UTC
Labels: bug, duplicate, enhancement
